apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danify

resources:
  - ../base/danify-landing
  - ../base/danify-fe
  - ../base/danify-be
  - ../base/postgresql
  - ingress.yaml
  - basic-auth-secret.yaml
  # ghcr-secret.yaml - managed outside ArgoCD

images:
  - name: danify-landing
    newName: ghcr.io/danify-cz/danify-landing
    newTag: "1.0.0" # danify-landing
  - name: danify-fe
    newName: ghcr.io/danify-cz/danify-fe
    newTag: "1.0.0" # danify-fe
  - name: danify-api
    newName: ghcr.io/danify-cz/danify-api
    newTag: "1.0.0" # danify-api

patches:
  - target:
      kind: Deployment
      name: danify-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
