apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danify

resources:
  - ../base/danify-landing
  - ../base/danify-fe
  - ../base/danify-be
  - ../base/postgresql
  - ingress.yaml
  - ghcr-secret.yaml

images:
  - name: danify-landing
    newName: ghcr.io/danify-cz/danify-landing
    newTag: preview
  - name: danify-fe
    newName: ghcr.io/danify-cz/danify-fe
    newTag: preview
  - name: danify-api
    newName: ghcr.io/danify-cz/danify-api
    newTag: preview

patches:
  - target:
      kind: Deployment
      name: danify-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "192Mi"
            cpu: "75m"
          limits:
            memory: "384Mi"
            cpu: "300m"
