apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danify

resources:
  - ../base/danify-landing
  - ../base/danify-fe
  - ../base/danify-be
  - ../base/postgresql
  - ingress.yaml
  - danify-fe-config.yaml
  # ghcr-secret.yaml - managed outside ArgoCD

images:
  - name: danify-landing
    newName: ghcr.io/danify-cz/danify-landing
    newTag: "dev-3c45510" # danify-landing
  - name: danify-fe
    newName: ghcr.io/danify-cz/danify-fe
    newTag: "dev-3c45510" # danify-fe
  - name: danify-api
    newName: ghcr.io/danify-cz/danify-api
    newTag: "dev-3c45510" # danify-api

patches:
  - target:
      kind: Deployment
      name: danify-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "192Mi"
            cpu: "75m"
          limits:
            memory: "384Mi"
            cpu: "300m"
