apiVersion: v1
kind: Service
metadata:
  name: danify-fe
  labels:
    app.kubernetes.io/name: danify-fe
    app.kubernetes.io/component: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: danify-fe
