apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danify

resources:
  - ../base/danify-landing
  - ../base/danify-fe
  - ../base/danify-be
  - ../base/postgresql
  - ingress.yaml
  - danify-fe-config.yaml
  # ghcr-secret.yaml - managed outside ArgoCD

images:
  - name: danify-landing
    newName: ghcr.io/danify-cz/danify-landing
    newTag: dev-7e3ccca # danify-landing
  - name: danify-fe
    newName: ghcr.io/danify-cz/danify-fe
    newTag: dev-2f5e1e4 # danify-fe
  - name: danify-api
    newName: ghcr.io/danify-cz/danify-api
    newTag: dev-913f8af # danify-api

patches:
  - target:
      kind: ConfigMap
      name: danify-api-config
    patch: |-
      - op: add
        path: /data/BETTER_AUTH_URL
        value: "https://api.dev.danify.cz:9443"
      - op: add
        path: /data/TRUSTED_ORIGINS
        value: "https://app.dev.danify.cz:9443"
