apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danify

resources:
  - ../base/danify-landing
  - ../base/danify-fe
  - ../base/danify-be
  - ../base/postgresql
  - ingress.yaml
  - danify-fe-config.yaml
  # ghcr-secret.yaml - managed outside ArgoCD

images:
  - name: danify-landing
    newName: ghcr.io/danify-cz/danify-landing
    newTag: dev-b77474d # danify-landing
  - name: danify-fe
    newName: ghcr.io/danify-cz/danify-fe
    newTag: dev-6bff998 # danify-fe
  - name: danify-api
    newName: ghcr.io/danify-cz/danify-api
    newTag: dev-b77474d # danify-api
